### ISSUE TITLE
能否添加一个隐藏状态栏刷新按钮的按键？

### ISSUE THREAD

**Issue by AndyLinyeye** [PKM-er/obsidian-editing-toolbar#127]

**Comment by cumany** [comment]
使用下面的片段即可解决问题

Applying this css snippet will fix it
```css
.status-bar-item.plugin-editing-toolbar{
display:none
}
```
