### ISSUE TITLE
Button Resize

### ISSUE THREAD

**Issue by feedhopper** [PKM-er/obsidian-editing-toolbar#203]
The button size is very small on my very large screen. I would like to resize the buttons. I used the CSS snippet from before, but it doesn't work anymore since 3.x

Any help would be GREATLY appreciated

Old snippet can be found here:

https://github.com/PKM-er/obsidian-editing-toolbar/issues/35

**Comment by juestchaos** [comment]
Maybe you can try this content and update it to replace the content of #35 originally.

:is(#editingToolbarModalBar,#editingToolbarCommandItem) svg{
height: 32px !important;
width: 32px !important;
max-width: 32px  !important;
max-height: 32px  !important;
}

**Comment by feedhopper** [comment]
Hey @juestchaos !

Thanks a lot for your suggestion. Does this work on your machine? It does not on mine, unfortunately. Just to make sure - I tried this - deliberately with more extreme settings to make sure I see a difference:

```
:is(#editingToolbarModalBar,#editingToolbarCommandItem) svg{
height: 64px !important;
width: 64px !important;
max-width: 64px  !important;
max-height: 64px  !important;
}
```

**Comment by juestchaos** [comment]
Yes, this is normal. If there is anything abnormal with it, please check whether the CSS snippets are not enabled, or restart Obsidian (OB) to make it take effect.

**Comment by juestchaos** [comment]
![Image](https://github.com/user-attachments/assets/31558e08-3455-44c2-96b6-26d75f316d57)

**Comment by feedhopper** [comment]
Oh wow, I have no idea why at first it did not work. Now it does THANKS again!

I just wanted to get back to anyone looking for something similar. This is my final snippet:

```css
/* ------------------------------
General Settings
------------------------------ */
#editingToolbarModalBar {
  display: grid !important;
  grid-template-columns: repeat(20, 38px) !important;
  gap: 1px !important;
  /* entfernt 'opacity: 0.9; !important;' – Syntax: opacity: 0.9 !important; */
}

:is(#editingToolbarModalBar, .editingToolbarCommandItem) svg {
  height: 26px !important;
  width: 28px !important;
  stroke-width: 1.4 !important;
}

/* ------------------------------
Light Theme
------------------------------ */
body.theme-light #editingToolbarModalBar {
  background-color: #d1cbc2 !important; /* Hintergrund der Toolbar */
}

body.theme-light .editingToolbarCommandItem {
  background-color: #d1cbc2 !important; /* Hintergrund der Buttons (bitte gültigen Hex-Code nutzen) */
  opacity: 0.5 !important;
}

body.theme-light #editingToolbarModalBar svg {
  stroke: #000000 !important; /* Stroke-Farbe der Icons */
}

/* ------------------------------
Dark Theme
------------------------------ */
body.theme-dark #editingToolbarModalBar {
  background-color: #2b3b36 !important; /* Beispiel: dunkle Hintergrundfarbe */
}

body.theme-dark .editingToolbarCommandItem {
  background-color: #2b3b36 !important; /* Beispiel: dunkler Button-Hintergrund */
}

body.theme-dark #editingToolbarModalBar svg {
  stroke: #c3dbd4 !important; /* Helle Stroke-Farbe für die Icons im dunklen Modus */
}

```
